name: GitHub Actions Windows
run-name: ${{ github.actor }} Windows test
on: [push]
jobs:
  Test:
    runs-on: windows-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    
    - name: Вывод содержимого директории
      run: dir ${{ github.workspace }}
    
    - name: Setup CMake
      uses: threeal/cmake-action@v2.1.0
    
    - name: Компиляция
      run: cmake --build build --config Release
    
    - name: Вывод содержимого директории
      run: dir ${{ github.workspace }}\build
    
    - name: Тест
      working-directory: ./build/hello_world_application/Release
      run: .\hello.exe
